package user_interface_layer.presenter_manager.display_choose_stratification_variable;

import use_cases.modify_study_parameters.ChooseStratificationInputData;

public interface DisplayChooseStratificationVariableInterface {
    void presentChooseStratificationVariableScreen(ChooseStratificationInputData data);
}
