package user_interface_layer.presenter_manager.display_versioned_answers_of_questionnaire;

import use_cases.questionnaire_answer_data_request.CheckQuestionnaireVersionedAnswerInputData;

public interface DisplayVersionedAnswersOfQuestionnaireInterface {
    void presentVersionedAnswersOfQuestionnaireScreen(CheckQuestionnaireVersionedAnswerInputData data);
}
