package user_interface_layer.presenter_manager.display_versioned_answers_of_questionnaire;

import use_cases.fetch_questionnaire_versioned_answer_viewing.CheckQuestionnaireVersionedAnswerInputData;

public interface DisplayVersionedAnswersOfQuestionnaireInterface {
    void presentVersionedAnswersOfQuestionnaireScreen(CheckQuestionnaireVersionedAnswerInputData data);
}
