package user_interface_layer.presenter_manager.display_participant_answer_questionnaire_panel;

import use_cases.answer_questionnaire_data_request.ParticipantAnswerQuestionnairePanelInputData;

public interface DisplayParticipantAnswerQuestionnairePanelInterface {
    void presentParticipantAnswerQuestionnairePanel(ParticipantAnswerQuestionnairePanelInputData data);
}
