package user_interface_layer.presenter_manager.display_versioned_answer;

import use_cases.fetch_questionnaire_versioned_answer_viewing.CheckQuestionnaireVersionedAnswerInputData;

public interface DisplayVersionedAnswerInterface {
    void presentVersionedAnswersOfQuestionnaireScreen(CheckQuestionnaireVersionedAnswerInputData data);
}
