package user_interface_layer.presenter_manager.display_versioned_answer;

import use_cases.fetch_versioned_answer.FetchVersionedAnswerResponseModel;

public interface DisplayVersionedAnswerInterface {
    void presentVersionedAnswersOfQuestionnaireScreen(FetchVersionedAnswerResponseModel data);
}
